Create new React frontend for Nebari
nebari-dev/jhub-apps pull request #16
Opened 2023-11-17 17:03 UTC by jbouder

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [x] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [x] Did you add new tests?

## Documentation

- Added README to `ui` directory with instructions on running locally, development, and testing

## Any other comments?
- This update includes the base homepage updates created in React
- This update does not include the following React UI functionality: 
  - Create App, currently the existing panel app creation form is used
  - Edit, delete, start, stop functionality
  - Search functionality
- Future styling is to be expected

## Screenshots
<img width="1714" alt="Screenshot 2023-11-17 at 11 49 42 AM" src="https://github.com/nebari-dev/jhub-apps/assets/61591423/962b0f65-4dac-4c0d-bc54-053c08555b9c">
<img width="1713" alt="Screenshot 2023-11-17 at 11 49 54 AM" src="https://github.com/nebari-dev/jhub-apps/assets/61591423/c4582c7a-c7f8-4546-9925-e00b9e833c38">

2023-11-17 17:10 UTC, jbouder commented on jupyterhub_config.py
> +        },
Currently the Service buttons are populated with default JupyterHub services. These are added to provide a template for adding more as needed

2023-11-17 17:10 UTC, jbouder commented on jupyterhub_config.py
> +c.JupyterHub.default_url = "/hub/home"
This ensures that a user is redirected to the homepage when they click the top right logo, are are directed to the default_url by some JupyterHub mechanism

2023-11-21 08:51 UTC, aktech requested changes

2023-11-21 15:50 UTC, jbouder commented on .vscode/extensions.json
> +{
Removed

2023-11-21 15:50 UTC, jbouder commented on jhub_apps/templates/page.html
> +  <a href="{{base_url}}home {% if cdsdashboards_restricted %}-cds{% endif %}"
This file was copied from the original nebari page template, so it was a carry over. Removed as it is no longer applicable.

2023-11-21 15:54 UTC, jbouder commented on ui/README.md
> +http://localhost:8080/hub/home
Its appears to be loading fine for me...will contact offline.
![Uploading Screenshot 2023-11-21 at 10.52.24 AM.png…]()

2023-11-21 19:57 UTC, merged