UI App Table 386
nebari-dev/jhub-apps pull request #219
Opened 2024-04-08 19:38 UTC by kildre

Created a new AppTable component. 
## Reference Issues or PRs
https://gitlab.jatic.net/jatic/team-metrostar/t-e-platform/-/issues/386

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [X] Did you test the pull request locally?
- [X] Did you add new tests?

## Documentation

### Access-centered content checklist

#### Text styling

- [X] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [X] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [X] If the content were to be read as plain text, it still makes sense, and no information is missing.

## Any other comments?

2024-04-10 23:41 UTC, jbouder requested changes
Mostly cleanup

2024-04-10 23:41 UTC, jbouder commented on ui/package.json
> +    "@mui/x-data-grid": "^7.1.1",
This should be removed as it seems to be breaking the MUI Core Switch

2024-04-10 23:41 UTC, jbouder commented on ui/src/data/api.ts
> +  name: 'Longwaithe Dickenson',
Who is this? ...just curious :)

2024-04-10 23:41 UTC, jbouder commented on ui/src/pages/home/apps-section/apps-section.tsx
> +    console.log('APPSa', apps);
Remove this

2024-04-10 23:41 UTC, jbouder commented on ui/src/pages/home/home.tsx
> +  // const [updatedApps, setUpdatedApps] = useState<JhApp[]>(apps); // Added updatedApps state
Remove this

2024-04-10 23:41 UTC, jbouder commented on ui/src/pages/home/home.tsx
> +      // setAppStatus('Error'); // Set status back to Ready if there's an error
Remove this

2024-04-10 23:41 UTC, jbouder commented on ui/src/pages/home/home.tsx
> +  const handleStartRequst = async ({ id }: AppQueryPostProps) => {
Request spelled wrong, make sure to update the other instances as well.

2024-04-10 23:41 UTC, jbouder commented on ui/src/pages/home/home.tsx
> +  const handleDeleteRequst = async ({ id, remove }: AppQueryDeleteProps) => {
Request spelled wrong

2024-04-10 23:41 UTC, jbouder commented on ui/src/pages/home/home.tsx
> +  const handleStopRequst = async (id: string) => {
Request spelled wrong

2024-04-10 23:41 UTC, jbouder commented on ui/src/pages/home/home.tsx
> +      // setAppStatus('Error'); // Reflect an error state
Remove this

2024-04-10 23:41 UTC, jbouder commented on ui/src/pages/home/home.tsx
> +      // setAppStatus('Error'); // Reflect an error state
Remove this

2024-04-10 23:41 UTC, jbouder commented on ui/src/pages/home/home.tsx
> +          }
Remove these console logs

2024-04-10 23:41 UTC, jbouder commented on ui/src/store.ts
> +// });
Remove this

2024-04-10 23:41 UTC, jbouder commented on ui/src/pages/home/apps-section/app-table/app-table.test.tsx
> +    console.log('EDIT BUTTON LENGTH', editButtons.length);
Remove this

2024-04-10 23:57 UTC, jbouder commented on ui/src/pages/home/apps-section/app-table/app-table.tsx
> +                    </Button>
These buttons should be visible and/or disabled as follows:

- Stop Icon: if app.status === "Running"
-- Disable button if Shared
- Start Icon: show in all other cases
-- Disable if app.status === "Pending" or app.status === "Unknown"
- Edit Icon
-- Disable if Shared
- Delete Icon
-- Disable if Shared

2024-04-11 00:15 UTC, kildre commented on ui/src/data/api.ts
> +  name: 'Longwaithe Dickenson',
Just a made up name.

2024-04-11 14:11 UTC, jbouder approved these changes
🚀

2024-04-11 14:20 UTC, merged