updated form description field. added custom logic and styling
nebari-dev/jhub-apps pull request #257
Opened 2024-05-01 15:17 UTC by kildre

## Reference Issues or PRs

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

## Documentation

### Access-centered content checklist

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

## Any other comments?

2024-05-06 11:29 UTC, aktech commented
@kildre can you merge main and see if that fixes CI issues? I just merged a PR for the same.

2024-05-06 13:29 UTC, kildre commented
@aktech I'll do that.

2024-05-06 14:31 UTC, aktech commented
The test failures are genuine failures. The JupyterHub doesn't loads:

<img width="1104" alt="Screenshot 2024-05-06 at 3 30 05 pm" src="https://github.com/nebari-dev/jhub-apps/assets/5647941/8b73a816-dab8-4fe1-b91c-d28eb10fb534">

Console errors (Its unable to find static files, as you have moved them):

<img width="1920" alt="Screenshot 2024-05-06 at 3 29 49 pm" src="https://github.com/nebari-dev/jhub-apps/assets/5647941/733f7725-cadd-4108-b432-50720bb631b3">

2024-05-08 14:18 UTC, jbouder requested changes
Great work! Need to update a few things.

2024-05-08 14:18 UTC, jbouder commented on ui/src/components/app-form/app-form.tsx
> +      description: formData?.user_options.description || '',
These shouldn't be set here, they should be set in the useEffect here: https://github.com/nebari-dev/jhub-apps/blob/adfd708310c970afbe935b49b185eb2fa5174bac/ui/src/components/app-form/app-form.tsx#L342

2024-05-08 14:18 UTC, jbouder commented on ui/src/components/app-form/app-form.tsx
> +        console.log('value', value.length, '/', exceedLength);
Remove this

2024-05-08 14:18 UTC, jbouder commented on ui/src/components/app-form/app-form.tsx
> +      console.log('formData', formData);
Remove this

2024-05-08 16:12 UTC, kildre commented on ui/src/components/app-form/app-form.tsx
> +      console.log('formData', formData);
Removed

2024-05-08 19:17 UTC, kildre reviewed
Made updates

2024-05-08 19:51 UTC, jbouder approved these changes
💯

2024-05-08 20:08 UTC, merged