Fix wrong mention of jupyterhub managed service
nebari-dev/jhub-apps pull request #527
Opened 2024-11-13 16:51 UTC by viniciusdc

## Reference Issues or PRs

## What does this implement/fix?

There was an error in which type of jupyterhub service JhubAps belonged to

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

## Documentation

### Access-centered content checklist

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

## Any other comments?

2024-11-13 16:52 UTC, viniciusdc commented
the rest of the docs is correct, just that part was wrong... funny enough, just after that line I say its a hub managed service and even described the command that is ran

2024-11-14 13:12 UTC, aktech requested changes
Looks good, other than a minor grammar nitpick.

2024-11-14 13:12 UTC, aktech commented on docs/docs/concepts/infrastructure-architecture.mdx
> +JHub Apps, also known as JupyterHub (JHub) App Launcher, is an [JupyterHub-Managed Service](https://jupyterhub.readthedocs.io/en/stable/reference/services.html#launching-a-hub-managed-service) design
```suggestion
JHub Apps, also known as JupyterHub (JHub) App Launcher, is a [JupyterHub-Managed Service](https://jupyterhub.readthedocs.io/en/stable/reference/services.html#launching-a-hub-managed-service) designed to enable users to launch various server types including API services, any generic Python command, standard JupyterLab instances, and dashboards such as Panel, Bokeh, and Streamlit.
```

2025-01-16 16:43 UTC, aktech approved these changes

2025-01-16 16:50 UTC, merged